version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    environment:
      JVM_OPTS: -Xmx512m
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run: gradle assemble
      - run: gradle test
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
      - store_artifacts:
          path: build/libs
          destination: libs
